 
package sergical_shop6;

  
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class Welcome_PAge extends javax.swing.JFrame {

 
      Connection ct=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement st=null;
    public Welcome_PAge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(61, 42, 127));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bil.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 10, 740, 190);

        jProgressBar1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(270, 626, 813, 20);

        jProgressBar2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(270, 626, 813, 20);

        jProgressBar3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(jProgressBar3);
        jProgressBar3.setBounds(60, 330, 600, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 460);

        setSize(new java.awt.Dimension(742, 452));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
   
    public static void main(String args[]) {
      
          Welcome_PAge ff=new Welcome_PAge();  
       ff.setVisible(true);
         for (int i = -1; i <=99;) {
             i++;
                 try {
                     Thread.sleep(40); 
                      jProgressBar1.setValue(i);
                      if(i==100){
          LogingPage f =new LogingPage();
          f.setVisible(true);
               
                ff.setVisible(false);
             }
                 } catch (InterruptedException ex) {
                     Logger.getLogger(Welcome_PAge.class.getName()).log(Level.SEVERE, null, ex);
                 }

            
           
             
}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JProgressBar jProgressBar1;
    private static javax.swing.JProgressBar jProgressBar2;
    private static javax.swing.JProgressBar jProgressBar3;
    // End of variables declaration//GEN-END:variables
}
